version: "3.9"

networks:
  mock-server-net:
    driver: bridge

services:
  api:
    container_name: mock-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - mock-server-net
