// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Teo Martin Toledo",
            "email": "teootoledo@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mock": {
            "post": {
                "description": "Set mock response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mock"
                ],
                "summary": "Set mock response",
                "parameters": [
                    {
                        "description": "Mock creation details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resources.CreateMockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mock response set successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "resources.CreateMockRequest": {
            "type": "object",
            "required": [
                "endpoint",
                "method",
                "status-code"
            ],
            "properties": {
                "endpoint": {
                    "type": "string",
                    "example": "/api/example"
                },
                "method": {
                    "type": "string",
                    "example": "POST"
                },
                "payload": {
                    "type": "string",
                    "example": "{\"example\":\"example\"}"
                },
                "status-code": {
                    "type": "integer",
                    "example": 200
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Mock Server API",
	Description:      "API for mocking responses",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
